name: New PR
on:
  pull_request_target:
    types:
      - closed
permissions:
  pull-requests: write
jobs:
  pr:
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'next' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create -H next -B main -t 'chore: release' -b ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
