name: Release
on:
  pull_request_target:
    types:
      - closed
jobs:
  Release:
    permissions:
      contents: write
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'next'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Release
        run: |
          npm i -D semantic-release @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR:
    permissions:
      pull-requests: write
    needs:
      - Release
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create -H next -B main -t 'chore: release' -b '' -R ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
