name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Release
        run: |
          npm i -D semantic-release @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
          npx semantic-release
